config/routes.rb
RailsExpenseReportMongo::Application.routes.draw do
  get "logout" => "session#destroy", :as => "logout" 
  get "login" => "session#new", :as => "login"
  post "login" => "session#create"
  get "signup" => "users#new", :as => "signup"

  resources :users
  
  resources :expenses do
    member do
      put :update_status
    end

    collection do
      get :approvals
    end

  end 

  root :to => "session#new"

end

app/models/expense.rb
class Expense
  include Mongoid::Document

  field :description, type: String
  field :amount, type: Float
  field :status, type: String, default: EXPENSE_STATUS[0]
  field :date, type: Date
  field :attachment, type: String 

  mount_uploader :attachment, AttachmentUploader

  belongs_to :user
  belongs_to :expense_type

  validates :description, :expense_type_id, :status, :user_id, :date, :presence => true
  validates :amount, :numericality => {message: "is not valid"}

  scope :pending, where(:status => EXPENSE_STATUS[0])
end

app/models/expense_type.rb
class ExpenseType
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String

  has_many :expenses

  # Validation for the name field
  validates :name, :presence => true, :uniqueness => true
end

app/models/user.rb
class User
  include Mongoid::Document

  has_many :expenses, :dependent => :destroy

  authenticates_with_sorcery!

  field :username, type: String
  field :crypted_password, type: String
  field :salt, type: String
  field :role, type: String, default: USER_ROLES[1]

  attr_accessor :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username
  validates_uniqueness_of :username

  def is_admin?
    role.eql? USER_ROLES[0]    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def check_admin_access
  	redirect_to expenses_path unless current_user.is_admin?  	
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
	before_filter :require_login, :get_pending_expenses
	before_filter :check_admin_access, :only => [:approvals, :update_status]

	def new
		# create a new expense object for the currentlyl logged in user.
		@expense = current_user.expenses.build
	end

	def create
		@expense = current_user.expenses.build(params[:expense])

		if @expense.save
			redirect_to expenses_path
		else	
			render "new"
		end
	end

	def index
		@expenses = current_user.expenses.includes(:expense_type).page(params[:page]).per(2)
	end

	def edit
		@expense = current_user.expenses.find(params[:id])
	end

	def update
		@expense = current_user.expenses.find(params[:id])

		if @expense.update_attributes(params[:expense])
			flash[:notice] = "Expense updated Successfully."

			redirect_to expenses_path
		else
			render "edit"
		end
	end

	def destroy
		current_user.expenses.find(params[:id]).destroy
		redirect_to :back
	end

	def approvals
		@expenses = Kaminari.paginate_array(Expense.pending.includes(:expense_type)).page(params[:page]).per(2)

		render "index"
	end

	def update_status
		@expense = Expense.find(params[:id])
		@expense.update_attribute(:status, params[:status])

		redirect_to :back
	end

	protected

	def get_pending_expenses
		@pending_expenses = Expense.pending if current_user.is_admin?	
	end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    if current_user
      redirect_to expenses_path
    end
  end

  def create
  	user = login(params[:username], params[:password], params[:remember_me])

  	if user
  		# Sorcery method to redirect the user to the private page that user requested before he was redirected to the login page
  		redirect_back_or_to expenses_path, :notice => "Logged In!!"
  	else
  		@error_message = "Invalid username or password"
  		render 'new'			
  	end
  end

  def destroy
  	# method provided by sorcery
  	logout
  	
  	redirect_to root_url, :notice => "Logged out!!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :require_login, :only => [:show]

  def new
  		@user = User.new
	end

  def create
	  @user = User.new(params[:user])	
  	if @user.save
  			redirect_to root_url, :notice => "Signed up!"
  	else
  			render :new		
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_status_class(expense)
	    status = expense.status
	    case status
		    when EXPENSE_STATUS[0]
		      ""
		    when EXPENSE_STATUS[1]
		      "green"
		    when EXPENSE_STATUS[2]
		      "red"
	    end
  	end

  	def get_status_image(expense)
	    status = expense.status
	    case status
		    when EXPENSE_STATUS[0]
		      "question-a"
		    when EXPENSE_STATUS[1]
		      "right-a"
		    when EXPENSE_STATUS[2]
		      "cross-a"
	    end
  	end

  	def get_cross_image
    	image_tag(asset_path("cross-b.png"), :class => "cross-b-img")
  	end

  	def form_heading_text
	    ['new', 'create'].include?(params[:action]) ? "Add New Expense" : "Edit Expense"
  	end

  	def submit_button_text
    	['new', 'create'].include?(params[:action]) ? "Add Expense" : "Update Expense"
  	end

  	def get_pointer
    	content_tag(:i, image_tag(asset_path 'arrow-right-a.png', :class => "arrow-right-a-img"),
                :class => "bg-arrow-right-a")
  	end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_expense.html.erb
<tr>
  <td>
    <h5 class="label-4"><%= I18n.localize(expense.date, :format => "%d-%I-%Y") if expense.date %></h5>
  </td>
  <td>
    <h5 class="label-4"><%= truncate(expense.expense_type.name, :length => 20) %></h5>
  </td>
  <td class="fixed-width">
    <h5 class="label-4">
      <%= truncate(expense.description, :length => 50) %>
      <% if expense.attachment? %>
        <%= link_to image_tag(asset_path('clip-b.png'), :class => 'clip-b-img flt-right'), expense.attachment.url, :target => "_blank" %>
      <% end %>
    </h5>
  </td>
  <% if params[:action].eql?("approvals") %>
    <td>
      <h5 class="label-4"><%= expense.user.username %></h5>
    </td>
  <% end %>
  <td>
    <h5 class="label-4">
      <i class="alt-a label-5 <%= get_status_class(expense) %>">
        <img class="<%= get_status_image(expense) %>-img" src='<%= asset_path "#{get_status_image(expense)}.png" %>'>
        <%= expense.status %>
      </i>

      <i class="alt-b label-6">
        <img class="<%= get_status_image(expense) %>-img" src='<%= asset_path "#{get_status_image(expense)}.png" %>'> <%= expense.status %>
        <% if current_user.is_admin? && params[:action].eql?("approvals") %>
          <span>
            <img class="arrow-down-b-img arrow-down-actions" src="<%= asset_path 'arrow-down-b.png' %>">
            <ul class="admin-actions" style="display: none;">
              <li>
                <img class="right-b-img" src="<%= asset_path 'right-a.png' %>">
                <%= link_to "Approve", update_status_expense_path(:id => expense.id, :status => EXPENSE_STATUS[1]), :method => :put %>
              </li>
              <li>
                <img class="cross-a-img" src="<%= asset_path 'cross-a.png' %>">
                <%= link_to "Reject", update_status_expense_path(:id => expense.id, :status => EXPENSE_STATUS[2]), :method => :put %>
              </li>
            </ul>
          </span>
        <% else %>
          <%= link_to(edit_expense_path(expense), :class => "bg-edit-b") do %>
            <img class="clip-b-img" src="<%= asset_path 'edit-a.png' %>">
          <% end %>
          <%= link_to get_cross_image.html_safe, expense_path(expense), :class => "bg-cross-b", :confirm => "Are you sure want to delete?", :method => :delete %>
        <% end %>
      </i>

    </h5>
  </td>
</tr>

app/views/expenses/_form.html.erb
<%= form_for @expense, :html => {:multipart => true, :class => "mtop80"} do |f| %>
  <% if @expense.errors.any? %>
    <div class="error_messages">
      <ul>
        <% for message in @expense.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="action-a">
    <%= f.label :description, :class => "label-name" %>
    <%= f.text_area :description, :class => "textbox-a", :placeholder => "description" %>
  </div>

  <div class="action-a">
    <%= f.label :amount, :class => "label-name" %>
    <%= f.text_field :amount, :class => "textbox-a dd-b flt-left mleft0", :style => "width: 185px;", :placeholder => "Amount like 210.50" %>

    <a class="label-7 flt-right" href="javascript:void(0)" id="attachment-holder"><img class="clip-a-img" src="<%= asset_path 'clip-a.png' %>"><span id="attachment-name">Attach Receipt</span> </a>
    <%= f.file_field :attachment, :style => "display: none;" %>
  </div>

  <div class="action-a">
    <%= f.label :expense_type_id, :class => "label-name" %>
    <%= collection_select(:expense, :expense_type_id, ExpenseType.all, :id, :name, options ={:prompt => "Select Expense Type"}, html_options = {:class =>"textbox-a dd-a mleft0"} ) %>

  </div>

  <div class="action-a">
    <%= f.label :date, "Generated on", :class => "label-name" %>
    <input type="text" name="expense[date]" placeholder="DD/MM/YY" id="date-field" class="textbox-a dd-b mleft0" style="width: 185px; cursor: pointer;" readonly="readonly" value="<%= @expense.date %>" />
  </div>
  <%= f.submit submit_button_text, :class => "btn-a add-expense-btn" %>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#attachment-holder').live('click', function(){
      $('#expense_attachment').trigger('click');
    });

    $("input[type='file']").change( function() {
      if($(this).val() == "")
        $('#attachment-name').html("Attach Receipt");
      else
        $('#attachment-name').html($(this).val().replace(/^.*\\/g, ''));
    });
  })
</script>

app/views/expenses/edit.html.erb
<%= render :partial => "expenses/form" %>

app/views/expenses/index.html.erb
<table class="table-a">
	<thead>
  <tr>
    <td class="td-a">
      <h5 class="label-3">Date</h5>
    </td>
    <td class="td-b">
      <h5 class="label-3">Type</h5>
    </td>
    <td class="td-c">
      <h5 class="label-3">Description</h5>
    </td>
    <% if params[:action].eql?("approvals") %>
      <td>
        <h5 class="label-3">Created By</h5>
      </td>
    <% end %>
    <td  class="td-d">
      <h5 class="label-3">Status</h5>
    </td>
  </tr>
  </thead>
  <tbody>
  	<%= render @expenses %>
  </tbody>
</table>
<div class="pagination pagination-1">
  <%= paginate @expenses %>
</div>

app/views/expenses/new.html.erb
<%= render :partial => "expenses/form" %>

app/views/layouts/_actions_nav.html.erb
<div id="nav">
	<ul>
		<% if current_user.is_admin? %>
			<li class="<%= params[:action].eql?('approvals') ? 'selected' : '' %>">
				<%= link_to "Approvals (#{@pending_expenses.count})", approvals_expenses_path %>
			</li>
		<% end %>

		<li class="<%= params[:action].eql?('index') ? 'selected' : '' %>">
			<%= link_to "My Expenses", expenses_path %>
		</li>
		<li class="<%= ['index', 'approvals'].include?(params[:action]) ? 'selected' : '' %>">
			<%= link_to "New Expense", new_expense_path %>
		</li>
	</ul>
</div>

app/views/layouts/_header_nav.html.erb
<div class="inside-nav">
	<div class="logo">
		<img src="<%= asset_path 'logo.png'%>" alt="">
	</div>
	<ul class="nav-a">
		<% if current_user %>
			<li><a href="javascript:void(0)">Hi <%= current_user.username %></a></li>
			<li>|</li>
			<li><%= link_to "Logout", logout_path %></li>
		<% else %>
			<li>
				<%= link_to "Login", login_path, :class => params[:controller].eql?('sessions') ? 'selected' : '' %>
			</li>
			<li>|</li>
			<li><%= link_to "Signup", signup_path, :class => params[:controller].eql?('users') ? 'selected' : '' %></li>
		<% end %>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsExpenseReportMongo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="contentWrapper">
		<div class="blue-b">
			<%= render :partial => 'layouts/header_nav' %>
		</div>
		<% if current_user %>
			<%= render :partial =>  'layouts/actions_nav' %>
		<% end %>
		<div class="mc-a">
			<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/session/new.html.erb
<div class="signing-form">
	<% if @error_message %>
		<div class="error_messages signing-error">
			<ul>
				<li><%= @error_message %></li>
			</ul>
		</div>
	<% else %>
		<% flash.each do |name, message| %>	
			<%= content_tag :div, message, :id => "flash_#{name}" %>
		<% end %>	
	<% end %>

	<%= form_tag login_path do %>
		<div>
			<label for="">UserName</label>
			<%= text_field_tag :username, params[:username], :class => "textbox-a", :placeholder => "UserName" %>
		</div>
		<div>
			<label for="">Password</label>
			<%= password_field_tag :password, '', :class => "textbox-a", :placeholder => "Password" %>
		</div>
		<div>
			<%= submit_tag "Log In", :class => "btn-a" %>
		</div>
	<% end %>	
</div>

app/views/users/new.html.erb
<div class="signing-form">
	<%= form_for @user do |f| %>
		<% if @user.errors.any? %>
			<div class="error_messages signing-error">
				<ul>
					<% for message in @user.errors.full_messages %>
						<li>
					  		<%= message %>
					  	</li>		    
					<% end %>					
				</ul>
			</div>		
		<% end %>
		<div>
			<label for="">Username</label>
			<%= f.text_field :username, :class => "textbox-a", :placeholder => "UserName" %>
		</div>
		<div>
			<label for="">Password</label>
			<%= f.password_field :password, :class => "textbox-a", :placeholder => "Password" %>
		</div>
		<div>
			<label for="">Password Confirmation</label>
			<%= f.password_field :password_confirmation, :class => "textbox-a", :placeholder => "Password Confirmation" %>
		</div>
		<div>
			<%= f.submit "Sign Up", :class => "btn-a" %>
		</div>
	<% end %>
</div>

app/views/users/show.html.erb
<h2>Welcome to Expense Report Application</h2>
<p>
	Hello <%= current_user.username %>, <br/>
</p>